apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - image: mfanjie/jupyter
        name: jupyter
        volumeMounts:
        - mountPath: /data/jupyter-model
          name: jupyter-model
      volumes:
      - hostPath:
          path: /data/jupyter-model
          type: Directory
        name: jupyter-model
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter
  type: NodePort
