apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - image: mfanjie/jupyter
        name: jupyter
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter
  type: NodePort
